export const locationsOfInterest = [
    // Glavna mjesta od interesa
    "Tinja",
    "Tinja Donja",
    "Tinja Gornja",
    "Previle",
    "Previle Bare I",
    "Previle Bare II",
    "Lisovići",
    "Brezik",
    "Brezje",
    "Brezje Sejdinovići",
    "Brezje Hodžići",
    "Brezje Šumarak",
    "Brezje Ekonimija",
    "Zahirovići",
    "Potpeć",
    "Podpeć",
    "Donji Potpeć",
    "Gornji Potpeć",
    "Donji Podpeć",
    "Gornji Podpeć",
    "Puštine",
    "Dragunja",
    "Donja Dragunja",
    "Srednja Dragunja",
    "Gornja Dragunja",
    "Miljevina",
    "Luka",
    "Klanac",
    "Polja",
    "Magistralni Put M",
    "Magistralni Put M 18",
    "Karaula",
    "Staro Selo",

    // Okolna mjesta i naselja
    "Podorašje",
    "Jasenica",
    "Crveno Brdo",
    "Straža",
    "Duboki Potok",
    "Nacional",
    "Blagići",
    "Cvijanovići",
    "Osoje",
    "Luke",
    "Namlići",
    "Mešići",
    "Zukići",
    "Krušik",
    "Memići",
];
